//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RutaPazDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_RPREGUNTA
    {
        public TBL_RPREGUNTA()
        {
            this.TBL_RRESPUESTA = new HashSet<TBL_RRESPUESTA>();
        }
    
        public int IdPregunta { get; set; }
        public string TipoPregunta { get; set; }
        public string Enunciado { get; set; }
    
        public virtual ICollection<TBL_RRESPUESTA> TBL_RRESPUESTA { get; set; }
    }
}
