//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RutaDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_RMODULO
    {
        public TBL_RMODULO()
        {
            this.TBL_RPREGUNTA = new HashSet<TBL_RPREGUNTA>();
        }
    
        public int IdModulo { get; set; }
        public string NombreModulo { get; set; }
        public string FelicitacionModulo { get; set; }
        public string FelicitacionCompartir { get; set; }
    
        public virtual ICollection<TBL_RPREGUNTA> TBL_RPREGUNTA { get; set; }
    }
}
